/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seas.multinacional.principal;

import java.awt.BorderLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JPanel;
import seas.multinacional.gestionbd.GestionSql;
import seas.multinacional.modelo.Cliente;
import seas.multinacional.modelo.Producto;
import seas.multinacional.modelo.Vendedor;
import seas.multinacional.vistas.PanelAltaClientes;
import seas.multinacional.vistas.PanelAltaVendedores;
import seas.multinacional.vistas.PanelBajaClientes;
import seas.multinacional.vistas.PanelBajaVendedores;
import seas.multinacional.vistas.PanelEditaClientes;
import seas.multinacional.vistas.PanelEditaVendedores;
import seas.multinacional.vistas.PanelInicio;
import seas.multinacional.vistas.PanelListarClientes;
import seas.multinacional.vistas.PanelListarVendedores;
import seas.multinacional.vistas.PanelProductos;

/**
 *
 * @author maria
 */
public class MultinacionalFrame extends javax.swing.JFrame {

    private final ArrayList<Cliente> clientesGuardados;
    private final ArrayList<Vendedor> vendedoresGuardados;
    private final Producto[] PRODUCTOS;
    private int cantidad = 0;
    private Producto producto;
    private Cliente cliente;

    
    /**
     * Creates new form MultinationalFrame
     */
    public MultinacionalFrame() {
        initComponents();
        PRODUCTOS = getProductos();
        clientesGuardados = new ArrayList<>();
        vendedoresGuardados = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuVentas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuCategorias = new javax.swing.JMenu();
        menuItemProductos = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        menuItemAlta = new javax.swing.JMenuItem();
        menuItemEdita = new javax.swing.JMenuItem();
        menuItemBaja = new javax.swing.JMenuItem();
        menuItemListar = new javax.swing.JMenuItem();
        menuVendedores = new javax.swing.JMenu();
        menuItemAlta1 = new javax.swing.JMenuItem();
        menuItemEdita1 = new javax.swing.JMenuItem();
        menuItemBaja1 = new javax.swing.JMenuItem();
        menuItemListar1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        panelContenedor.setMaximumSize(new java.awt.Dimension(1000, 610));
        panelContenedor.setMinimumSize(new java.awt.Dimension(1000, 610));
        panelContenedor.setPreferredSize(new java.awt.Dimension(1000, 610));
        panelContenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelContenedor, java.awt.BorderLayout.CENTER);

        menuInicio.setText("Inicio");
        menuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuInicio);

        menuVentas.setText("Ventas");

        jMenuItem1.setText("Por día");
        menuVentas.add(jMenuItem1);

        jMenuItem2.setText("Por cliente");
        menuVentas.add(jMenuItem2);

        jMenuBar1.add(menuVentas);

        menuCategorias.setText("Productos");

        menuItemProductos.setText("Consulta y modificación de productos");
        menuItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProductosActionPerformed(evt);
            }
        });
        menuCategorias.add(menuItemProductos);

        jMenuBar1.add(menuCategorias);

        menuClientes.setText("Clientes");

        menuItemAlta.setText("Alta Cliente");
        menuItemAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAltaActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemAlta);

        menuItemEdita.setText("Editar Cliente");
        menuItemEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditaActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemEdita);

        menuItemBaja.setText("Baja Cliente");
        menuItemBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBajaActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemBaja);

        menuItemListar.setText("Lista de Clientes");
        menuItemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemListar);

        jMenuBar1.add(menuClientes);

        menuVendedores.setText("Vendedores");

        menuItemAlta1.setText("Alta Vendedor");
        menuItemAlta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlta1ActionPerformed(evt);
            }
        });
        menuVendedores.add(menuItemAlta1);

        menuItemEdita1.setText("Editar Vendedor");
        menuItemEdita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEdita1ActionPerformed(evt);
            }
        });
        menuVendedores.add(menuItemEdita1);

        menuItemBaja1.setText("Baja Vendedor");
        menuItemBaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBaja1ActionPerformed(evt);
            }
        });
        menuVendedores.add(menuItemBaja1);

        menuItemListar1.setText("Lista de Vendedores");
        menuItemListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListar1ActionPerformed(evt);
            }
        });
        menuVendedores.add(menuItemListar1);

        jMenuBar1.add(menuVendedores);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Métodos que cargan los paneles
    
    private void menuItemAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAltaActionPerformed
          cargarPanel(new PanelAltaClientes(this));
    }//GEN-LAST:event_menuItemAltaActionPerformed

    private void menuItemEditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditaActionPerformed
          cargarPanel(new PanelEditaClientes(this));
    }//GEN-LAST:event_menuItemEditaActionPerformed

    private void menuItemBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBajaActionPerformed
          cargarPanel(new PanelBajaClientes(this));

    }//GEN-LAST:event_menuItemBajaActionPerformed

    private void menuItemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarActionPerformed
          cargarPanel(new PanelListarClientes(this));
    }//GEN-LAST:event_menuItemListarActionPerformed

    private void menuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInicioMouseClicked
        cargarPanel(new PanelInicio(this));
    }//GEN-LAST:event_menuInicioMouseClicked

    private void menuItemAlta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlta1ActionPerformed
         cargarPanel(new PanelAltaVendedores(this));
    }//GEN-LAST:event_menuItemAlta1ActionPerformed

    private void menuItemEdita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEdita1ActionPerformed
        cargarPanel(new PanelEditaVendedores(this));
    }//GEN-LAST:event_menuItemEdita1ActionPerformed

    private void menuItemBaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBaja1ActionPerformed
        cargarPanel(new PanelBajaVendedores(this));
    }//GEN-LAST:event_menuItemBaja1ActionPerformed

    private void menuItemListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListar1ActionPerformed
        cargarPanel(new PanelListarVendedores(this));
    }//GEN-LAST:event_menuItemListar1ActionPerformed

    private void menuItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProductosActionPerformed
        cargarPanel(new PanelProductos(this));
    }//GEN-LAST:event_menuItemProductosActionPerformed
  
    // Getters and Setters
    
    public ArrayList<Cliente> getClientesGuardados() {
        return clientesGuardados;
    }
    
    public ArrayList<Vendedor> getVendedoresGuardados() {
        return vendedoresGuardados;
    }
    
    public int getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    
    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    
    public Producto getProducto() {
        return producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    
    public Producto getProductoById(int id) {
        return PRODUCTOS[id-1];
    }
    
    /**
     * Método que devuelve un array con todos los productos de la bbdd
     * 
     * @return Producto[] Array con todos los productos de la bbdd
     */ 
    public Producto[] getProductos() {
        Producto[] productos = new Producto[39];
        String SQL_SELECT_PRODUCTOS ="SELECT id, idCategoria, nombre, precio FROM productos";
        try {
            GestionSql db = new GestionSql();
            Statement stmt = db.conn.createStatement();
            ResultSet rs = stmt.executeQuery(SQL_SELECT_PRODUCTOS);
            int i = 0;
            while(rs.next()){
                Producto aux = new Producto(rs.getInt(1),rs.getInt(2),rs.getString(3),rs.getFloat(4));
                productos[i] = aux;
                i++;
            }
            db.closeConnection();
        }catch(SQLException e){
            e.printStackTrace();
        }
        return productos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuCategorias;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenuItem menuItemAlta;
    private javax.swing.JMenuItem menuItemAlta1;
    private javax.swing.JMenuItem menuItemBaja;
    private javax.swing.JMenuItem menuItemBaja1;
    private javax.swing.JMenuItem menuItemEdita;
    private javax.swing.JMenuItem menuItemEdita1;
    private javax.swing.JMenuItem menuItemListar;
    private javax.swing.JMenuItem menuItemListar1;
    private javax.swing.JMenuItem menuItemProductos;
    private javax.swing.JMenu menuVendedores;
    private javax.swing.JMenu menuVentas;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Método que carga el panel pasado por parámetro
     * @param panel 
     */
    public void cargarPanel(JPanel panel) {
     panelContenedor.removeAll();
     panelContenedor.add(panel, BorderLayout.CENTER);
     panelContenedor.repaint();
     pack();
    }


}
