/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seas.multinacional.vistas;

import seas.multinacional.controlador.ServiceVendedor;
import seas.multinacional.principal.MultinacionalFrame;

/**
 *
 * @author maria
 */
public class PanelListarVendedores extends javax.swing.JPanel {
    
    
    private MultinacionalFrame frame;
    private ServiceVendedor acciones;

    /**
     * Creates new form PanelListarVendedores
     * @param frame 
     */
    public PanelListarVendedores(MultinacionalFrame frame) {
        this.frame = frame;
        initComponents();
        acciones = new ServiceVendedor(this);   
        lstVendedores.setModel(acciones.setVendedoresInList());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lstVendedores = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        lstVendedores.setToolTipText("");
        jScrollPane2.setViewportView(lstVendedores);

        jLabel1.setText("Clientes de la compañía (ordenados alfabéticamente):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstVendedores;
    // End of variables declaration//GEN-END:variables
}
