/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seas.multinacional.vistas;

import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import seas.multinacional.controlador.AccionesInicio;
import seas.multinacional.controlador.ServiceTicket;
import seas.multinacional.principal.MultinacionalFrame;

/**
 *
 * @author maria
 */
public class PanelInicio extends javax.swing.JPanel {

    private final MultinacionalFrame frame;
    private final AccionesInicio acciones;
    private final ServiceTicket serviceTicket;
    private final DefaultTableModel modeloTbl;
    private final ArrayList idProductos;
    private boolean descuentoAplicado;
    private final DateFormat dfDefault = DateFormat.getInstance();
    /**
     * Creates new form PanelInicio
     */

    /**
     * Constructor
     * @param frame 
     */
    public PanelInicio(MultinacionalFrame frame) {
        initComponents();
        this.frame = frame;
        this.acciones = new AccionesInicio(this);
        this.serviceTicket = new ServiceTicket();
        this.idProductos = new ArrayList();
        txtTicket.setText(Integer.toString(acciones.setTicket()));
        // Date fecha = new Date();
        //txtFecha.setText(fecha.toString());
        Date fecha = new Date();
        txtFecha.setText(dfDefault.format(fecha));
        cbVendedor.setModel(new javax.swing.DefaultComboBoxModel(acciones.getVendedores()));
        modeloTbl = (DefaultTableModel) tblCompra.getModel();
        descuentoAplicado = false;
    }
    
    public MultinacionalFrame getFrame() {
        return frame;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelInicio = new javax.swing.JPanel();
        pnlDatos = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        lblNumeroTicket = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblVendedor = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblCodigoCliente = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtTicket = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        cbVendedor = new javax.swing.JComboBox<>();
        txtCodigoCliente = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnCliente = new javax.swing.JButton();
        pnlCompra = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompra = new javax.swing.JTable();
        pnlSeleccion = new javax.swing.JPanel();
        pnlProductos = new javax.swing.JPanel();
        pnlCafes = new javax.swing.JPanel();
        btnAmericano = new javax.swing.JButton();
        btnLeche = new javax.swing.JButton();
        btnCappuccino = new javax.swing.JButton();
        btnMacchiato = new javax.swing.JButton();
        btnHelado = new javax.swing.JButton();
        btnFrapa = new javax.swing.JButton();
        btnEspresso = new javax.swing.JButton();
        btnMocha = new javax.swing.JButton();
        btnChocolate = new javax.swing.JButton();
        pnlBebidas = new javax.swing.JPanel();
        btnRefresco = new javax.swing.JButton();
        btnCerveza = new javax.swing.JButton();
        btnVino = new javax.swing.JButton();
        btnTinto = new javax.swing.JButton();
        btnZumo = new javax.swing.JButton();
        btnAgua = new javax.swing.JButton();
        pnlHamburguesas = new javax.swing.JPanel();
        btnSetas = new javax.swing.JButton();
        btnQueso = new javax.swing.JButton();
        btnBacon = new javax.swing.JButton();
        btnPicante = new javax.swing.JButton();
        btnHuevo = new javax.swing.JButton();
        btnTrufa = new javax.swing.JButton();
        btnPollo = new javax.swing.JButton();
        btnMiniBurger = new javax.swing.JButton();
        pnlBocadillos = new javax.swing.JPanel();
        btnSerranito = new javax.swing.JButton();
        btnCalamares = new javax.swing.JButton();
        btnVegetal = new javax.swing.JButton();
        btnAlbondigas = new javax.swing.JButton();
        pnlEnsaladas = new javax.swing.JPanel();
        btnMixta = new javax.swing.JButton();
        btnCesar = new javax.swing.JButton();
        btnFrutal = new javax.swing.JButton();
        pnlEntrantes = new javax.swing.JPanel();
        btnCroquetas = new javax.swing.JButton();
        btnPatatas = new javax.swing.JButton();
        btnEmpanadillas = new javax.swing.JButton();
        btnTortilla = new javax.swing.JButton();
        btnCaracoles = new javax.swing.JButton();
        pnlPostres = new javax.swing.JPanel();
        btnBizcocho = new javax.swing.JButton();
        btnTortitas = new javax.swing.JButton();
        btnMousseChoco = new javax.swing.JButton();
        btnMousseFresa = new javax.swing.JButton();
        pnlCategorias = new javax.swing.JPanel();
        btnCafes = new javax.swing.JButton();
        btnBebidas = new javax.swing.JButton();
        btnHamburguesas = new javax.swing.JButton();
        btnBocadillos = new javax.swing.JButton();
        btnEnsaladas = new javax.swing.JButton();
        btnEntrantes = new javax.swing.JButton();
        btnPostres = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        pnlNumeros = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnComa = new javax.swing.JButton();
        btnDescuento = new javax.swing.JButton();
        bntMas = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnArriba = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAbajo = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1000, 610));
        setMinimumSize(new java.awt.Dimension(1000, 610));
        setPreferredSize(new java.awt.Dimension(1000, 610));

        panelInicio.setBackground(new java.awt.Color(255, 255, 255));
        panelInicio.setMaximumSize(new java.awt.Dimension(1000, 610));
        panelInicio.setMinimumSize(new java.awt.Dimension(1000, 610));
        panelInicio.setPreferredSize(new java.awt.Dimension(1000, 610));
        panelInicio.setLayout(new java.awt.GridBagLayout());

        pnlDatos.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout pnlDatosLayout = new java.awt.GridBagLayout();
        pnlDatosLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        pnlDatosLayout.rowHeights = new int[] {0, 7, 0, 7, 0, 7, 0, 7, 0};
        pnlDatos.setLayout(pnlDatosLayout);

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/logo.png"))); // NOI18N
        lblLogo.setMaximumSize(new java.awt.Dimension(90, 56));
        lblLogo.setMinimumSize(new java.awt.Dimension(90, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlDatos.add(lblLogo, gridBagConstraints);

        lblEmpresa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEmpresa.setText("El Piscolabis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlDatos.add(lblEmpresa, gridBagConstraints);

        lblNumeroTicket.setText("Nº Ticket");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        pnlDatos.add(lblNumeroTicket, gridBagConstraints);

        lblFecha.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        pnlDatos.add(lblFecha, gridBagConstraints);

        lblVendedor.setText("Vendedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        pnlDatos.add(lblVendedor, gridBagConstraints);

        lblCliente.setText("Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 4;
        pnlDatos.add(lblCliente, gridBagConstraints);

        lblCodigoCliente.setText("Cod. Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 4;
        pnlDatos.add(lblCodigoCliente, gridBagConstraints);

        lblNombre.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 4;
        pnlDatos.add(lblNombre, gridBagConstraints);

        txtTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTicketActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        pnlDatos.add(txtTicket, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        pnlDatos.add(txtFecha, gridBagConstraints);

        cbVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVendedorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 8;
        pnlDatos.add(cbVendedor, gridBagConstraints);

        txtCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoClienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlDatos.add(txtCodigoCliente, gridBagConstraints);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        pnlDatos.add(txtNombre, gridBagConstraints);

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/cliente.png"))); // NOI18N
        btnCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCliente.setMaximumSize(new java.awt.Dimension(30, 30));
        btnCliente.setMinimumSize(new java.awt.Dimension(30, 30));
        btnCliente.setPreferredSize(new java.awt.Dimension(30, 30));
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 8;
        pnlDatos.add(btnCliente, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 10.0;
        panelInicio.add(pnlDatos, gridBagConstraints);

        pnlCompra.setBackground(new java.awt.Color(255, 255, 255));
        pnlCompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        pnlCompra.setMinimumSize(new java.awt.Dimension(450, 200));
        pnlCompra.setPreferredSize(new java.awt.Dimension(945, 200));
        pnlCompra.setRequestFocusEnabled(false);

        tblCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cant.", "Descripción", "Precio", "Dto.", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCompra.setMaximumSize(new java.awt.Dimension(2147483647, 234234));
        tblCompra.setMinimumSize(new java.awt.Dimension(75, 80));
        jScrollPane1.setViewportView(tblCompra);

        pnlCompra.add(jScrollPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelInicio.add(pnlCompra, gridBagConstraints);

        pnlSeleccion.setBackground(new java.awt.Color(255, 255, 255));
        pnlSeleccion.setMinimumSize(new java.awt.Dimension(922, 450));
        pnlSeleccion.setName(""); // NOI18N
        pnlSeleccion.setPreferredSize(new java.awt.Dimension(914, 500));

        pnlProductos.setMaximumSize(new java.awt.Dimension(500, 250));
        pnlProductos.setMinimumSize(new java.awt.Dimension(500, 250));
        pnlProductos.setPreferredSize(new java.awt.Dimension(500, 250));
        pnlProductos.setLayout(new java.awt.CardLayout());

        pnlCafes.setBackground(new java.awt.Color(255, 255, 255));
        pnlCafes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        pnlCafes.setAlignmentX(0.0F);
        pnlCafes.setAlignmentY(0.0F);
        pnlCafes.setEnabled(false);
        pnlCafes.setPreferredSize(new java.awt.Dimension(500, 185));
        pnlCafes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 4));

        btnAmericano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/americano.png"))); // NOI18N
        btnAmericano.setAlignmentY(0.0F);
        btnAmericano.setMaximumSize(new java.awt.Dimension(94, 77));
        btnAmericano.setMinimumSize(new java.awt.Dimension(94, 77));
        btnAmericano.setPreferredSize(new java.awt.Dimension(94, 77));
        btnAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmericanoActionPerformed(evt);
            }
        });
        pnlCafes.add(btnAmericano);

        btnLeche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/conleche.png"))); // NOI18N
        btnLeche.setAlignmentY(0.0F);
        btnLeche.setMaximumSize(new java.awt.Dimension(94, 77));
        btnLeche.setMinimumSize(new java.awt.Dimension(94, 77));
        btnLeche.setPreferredSize(new java.awt.Dimension(94, 77));
        btnLeche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecheActionPerformed(evt);
            }
        });
        pnlCafes.add(btnLeche);

        btnCappuccino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/cappuccino.png"))); // NOI18N
        btnCappuccino.setAlignmentY(0.0F);
        btnCappuccino.setMaximumSize(new java.awt.Dimension(94, 77));
        btnCappuccino.setMinimumSize(new java.awt.Dimension(94, 77));
        btnCappuccino.setPreferredSize(new java.awt.Dimension(94, 77));
        btnCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCappuccinoActionPerformed(evt);
            }
        });
        pnlCafes.add(btnCappuccino);

        btnMacchiato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/macchiato.png"))); // NOI18N
        btnMacchiato.setAlignmentY(0.0F);
        btnMacchiato.setMaximumSize(new java.awt.Dimension(94, 77));
        btnMacchiato.setMinimumSize(new java.awt.Dimension(94, 77));
        btnMacchiato.setPreferredSize(new java.awt.Dimension(94, 77));
        btnMacchiato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMacchiatoActionPerformed(evt);
            }
        });
        pnlCafes.add(btnMacchiato);

        btnHelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/helado.png"))); // NOI18N
        btnHelado.setAlignmentY(0.0F);
        btnHelado.setMaximumSize(new java.awt.Dimension(94, 77));
        btnHelado.setMinimumSize(new java.awt.Dimension(94, 77));
        btnHelado.setPreferredSize(new java.awt.Dimension(94, 77));
        btnHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeladoActionPerformed(evt);
            }
        });
        pnlCafes.add(btnHelado);

        btnFrapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/frapa.png"))); // NOI18N
        btnFrapa.setAlignmentY(0.0F);
        btnFrapa.setBorder(null);
        btnFrapa.setDefaultCapable(false);
        btnFrapa.setMaximumSize(new java.awt.Dimension(94, 77));
        btnFrapa.setMinimumSize(new java.awt.Dimension(94, 77));
        btnFrapa.setPreferredSize(new java.awt.Dimension(94, 77));
        btnFrapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrapaActionPerformed(evt);
            }
        });
        pnlCafes.add(btnFrapa);

        btnEspresso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/espresso.png"))); // NOI18N
        btnEspresso.setAlignmentY(0.0F);
        btnEspresso.setMaximumSize(new java.awt.Dimension(94, 77));
        btnEspresso.setMinimumSize(new java.awt.Dimension(94, 77));
        btnEspresso.setPreferredSize(new java.awt.Dimension(94, 77));
        btnEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspressoActionPerformed(evt);
            }
        });
        pnlCafes.add(btnEspresso);

        btnMocha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/mocha.png"))); // NOI18N
        btnMocha.setAlignmentY(0.0F);
        btnMocha.setMaximumSize(new java.awt.Dimension(94, 77));
        btnMocha.setMinimumSize(new java.awt.Dimension(94, 77));
        btnMocha.setPreferredSize(new java.awt.Dimension(94, 77));
        btnMocha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMochaActionPerformed(evt);
            }
        });
        pnlCafes.add(btnMocha);

        btnChocolate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/chocolate.png"))); // NOI18N
        btnChocolate.setAlignmentY(0.0F);
        btnChocolate.setMaximumSize(new java.awt.Dimension(94, 77));
        btnChocolate.setMinimumSize(new java.awt.Dimension(94, 77));
        btnChocolate.setPreferredSize(new java.awt.Dimension(94, 77));
        btnChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChocolateActionPerformed(evt);
            }
        });
        pnlCafes.add(btnChocolate);

        pnlProductos.add(pnlCafes, "cardCafes");

        pnlBebidas.setBackground(new java.awt.Color(255, 255, 255));
        pnlBebidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        pnlBebidas.setAlignmentX(0.0F);
        pnlBebidas.setAlignmentY(0.0F);
        pnlBebidas.setEnabled(false);
        pnlBebidas.setPreferredSize(new java.awt.Dimension(500, 250));
        pnlBebidas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 4));

        btnRefresco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/refresco.png"))); // NOI18N
        btnRefresco.setAlignmentY(0.0F);
        btnRefresco.setMaximumSize(new java.awt.Dimension(94, 77));
        btnRefresco.setMinimumSize(new java.awt.Dimension(94, 77));
        btnRefresco.setPreferredSize(new java.awt.Dimension(94, 77));
        btnRefresco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescoActionPerformed(evt);
            }
        });
        pnlBebidas.add(btnRefresco);

        btnCerveza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/cerveza.png"))); // NOI18N
        btnCerveza.setAlignmentY(0.0F);
        btnCerveza.setMaximumSize(new java.awt.Dimension(94, 77));
        btnCerveza.setMinimumSize(new java.awt.Dimension(94, 77));
        btnCerveza.setPreferredSize(new java.awt.Dimension(94, 77));
        btnCerveza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCervezaActionPerformed(evt);
            }
        });
        pnlBebidas.add(btnCerveza);

        btnVino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/vino.png"))); // NOI18N
        btnVino.setAlignmentY(0.0F);
        btnVino.setMaximumSize(new java.awt.Dimension(94, 77));
        btnVino.setMinimumSize(new java.awt.Dimension(94, 77));
        btnVino.setPreferredSize(new java.awt.Dimension(94, 77));
        btnVino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVinoActionPerformed(evt);
            }
        });
        pnlBebidas.add(btnVino);

        btnTinto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/tintodeverano.png"))); // NOI18N
        btnTinto.setAlignmentY(0.0F);
        btnTinto.setMaximumSize(new java.awt.Dimension(94, 77));
        btnTinto.setMinimumSize(new java.awt.Dimension(94, 77));
        btnTinto.setPreferredSize(new java.awt.Dimension(94, 77));
        btnTinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTintoActionPerformed(evt);
            }
        });
        pnlBebidas.add(btnTinto);

        btnZumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/zumo.png"))); // NOI18N
        btnZumo.setAlignmentY(0.0F);
        btnZumo.setMaximumSize(new java.awt.Dimension(94, 77));
        btnZumo.setMinimumSize(new java.awt.Dimension(94, 77));
        btnZumo.setPreferredSize(new java.awt.Dimension(94, 77));
        btnZumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZumoActionPerformed(evt);
            }
        });
        pnlBebidas.add(btnZumo);

        btnAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/agua.png"))); // NOI18N
        btnAgua.setAlignmentY(0.0F);
        btnAgua.setMaximumSize(new java.awt.Dimension(94, 77));
        btnAgua.setMinimumSize(new java.awt.Dimension(94, 77));
        btnAgua.setPreferredSize(new java.awt.Dimension(94, 77));
        btnAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAguaActionPerformed(evt);
            }
        });
        pnlBebidas.add(btnAgua);

        pnlProductos.add(pnlBebidas, "cardBebidas");

        pnlHamburguesas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlHamburguesas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 4));

        btnSetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/setas.png"))); // NOI18N
        btnSetas.setAlignmentY(0.0F);
        btnSetas.setMaximumSize(new java.awt.Dimension(94, 77));
        btnSetas.setMinimumSize(new java.awt.Dimension(94, 77));
        btnSetas.setPreferredSize(new java.awt.Dimension(94, 77));
        btnSetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetasActionPerformed(evt);
            }
        });
        pnlHamburguesas.add(btnSetas);

        btnQueso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/queso.png"))); // NOI18N
        btnQueso.setAlignmentY(0.0F);
        btnQueso.setMaximumSize(new java.awt.Dimension(94, 77));
        btnQueso.setMinimumSize(new java.awt.Dimension(94, 77));
        btnQueso.setPreferredSize(new java.awt.Dimension(94, 77));
        btnQueso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuesoActionPerformed(evt);
            }
        });
        pnlHamburguesas.add(btnQueso);

        btnBacon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/bacon.png"))); // NOI18N
        btnBacon.setAlignmentY(0.0F);
        btnBacon.setMaximumSize(new java.awt.Dimension(94, 77));
        btnBacon.setMinimumSize(new java.awt.Dimension(94, 77));
        btnBacon.setPreferredSize(new java.awt.Dimension(94, 77));
        btnBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaconActionPerformed(evt);
            }
        });
        pnlHamburguesas.add(btnBacon);

        btnPicante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/picante.png"))); // NOI18N
        btnPicante.setAlignmentY(0.0F);
        btnPicante.setMaximumSize(new java.awt.Dimension(94, 77));
        btnPicante.setMinimumSize(new java.awt.Dimension(94, 77));
        btnPicante.setPreferredSize(new java.awt.Dimension(94, 77));
        btnPicante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPicanteActionPerformed(evt);
            }
        });
        pnlHamburguesas.add(btnPicante);

        btnHuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/huevo.png"))); // NOI18N
        btnHuevo.setAlignmentY(0.0F);
        btnHuevo.setMaximumSize(new java.awt.Dimension(94, 77));
        btnHuevo.setMinimumSize(new java.awt.Dimension(94, 77));
        btnHuevo.setPreferredSize(new java.awt.Dimension(94, 77));
        btnHuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuevoActionPerformed(evt);
            }
        });
        pnlHamburguesas.add(btnHuevo);

        btnTrufa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/trufa.png"))); // NOI18N
        btnTrufa.setAlignmentY(0.0F);
        btnTrufa.setMaximumSize(new java.awt.Dimension(94, 77));
        btnTrufa.setMinimumSize(new java.awt.Dimension(94, 77));
        btnTrufa.setPreferredSize(new java.awt.Dimension(94, 77));
        btnTrufa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrufaActionPerformed(evt);
            }
        });
        pnlHamburguesas.add(btnTrufa);

        btnPollo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/pollo.png"))); // NOI18N
        btnPollo.setAlignmentY(0.0F);
        btnPollo.setMaximumSize(new java.awt.Dimension(94, 77));
        btnPollo.setMinimumSize(new java.awt.Dimension(94, 77));
        btnPollo.setPreferredSize(new java.awt.Dimension(94, 77));
        btnPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolloActionPerformed(evt);
            }
        });
        pnlHamburguesas.add(btnPollo);

        btnMiniBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/miniburger.png"))); // NOI18N
        btnMiniBurger.setAlignmentY(0.0F);
        btnMiniBurger.setMaximumSize(new java.awt.Dimension(94, 77));
        btnMiniBurger.setMinimumSize(new java.awt.Dimension(94, 77));
        btnMiniBurger.setPreferredSize(new java.awt.Dimension(94, 77));
        btnMiniBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiniBurgerActionPerformed(evt);
            }
        });
        pnlHamburguesas.add(btnMiniBurger);

        pnlProductos.add(pnlHamburguesas, "cardHamburguesas");

        pnlBocadillos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBocadillos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 4));

        btnSerranito.setAlignmentY(0.0F);
        btnSerranito.setMaximumSize(new java.awt.Dimension(94, 77));
        btnSerranito.setMinimumSize(new java.awt.Dimension(94, 77));
        btnSerranito.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlBocadillos.add(btnSerranito);

        btnCalamares.setAlignmentY(0.0F);
        btnCalamares.setMaximumSize(new java.awt.Dimension(94, 77));
        btnCalamares.setMinimumSize(new java.awt.Dimension(94, 77));
        btnCalamares.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlBocadillos.add(btnCalamares);

        btnVegetal.setAlignmentY(0.0F);
        btnVegetal.setMaximumSize(new java.awt.Dimension(94, 77));
        btnVegetal.setMinimumSize(new java.awt.Dimension(94, 77));
        btnVegetal.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlBocadillos.add(btnVegetal);

        btnAlbondigas.setAlignmentY(0.0F);
        btnAlbondigas.setMaximumSize(new java.awt.Dimension(94, 77));
        btnAlbondigas.setMinimumSize(new java.awt.Dimension(94, 77));
        btnAlbondigas.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlBocadillos.add(btnAlbondigas);

        pnlProductos.add(pnlBocadillos, "cardBocadillos");

        pnlEnsaladas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlEnsaladas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 4));

        btnMixta.setBackground(new java.awt.Color(255, 255, 255));
        btnMixta.setAlignmentY(0.0F);
        btnMixta.setMaximumSize(new java.awt.Dimension(94, 77));
        btnMixta.setMinimumSize(new java.awt.Dimension(94, 77));
        btnMixta.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlEnsaladas.add(btnMixta);

        btnCesar.setAlignmentY(0.0F);
        btnCesar.setMaximumSize(new java.awt.Dimension(94, 77));
        btnCesar.setMinimumSize(new java.awt.Dimension(94, 77));
        btnCesar.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlEnsaladas.add(btnCesar);

        btnFrutal.setAlignmentY(0.0F);
        btnFrutal.setMaximumSize(new java.awt.Dimension(94, 77));
        btnFrutal.setMinimumSize(new java.awt.Dimension(94, 77));
        btnFrutal.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlEnsaladas.add(btnFrutal);

        pnlProductos.add(pnlEnsaladas, "cardEnsaladas");

        pnlEntrantes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlEntrantes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 4));

        btnCroquetas.setAlignmentY(0.0F);
        btnCroquetas.setMaximumSize(new java.awt.Dimension(94, 77));
        btnCroquetas.setMinimumSize(new java.awt.Dimension(94, 77));
        btnCroquetas.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlEntrantes.add(btnCroquetas);

        btnPatatas.setAlignmentY(0.0F);
        btnPatatas.setMaximumSize(new java.awt.Dimension(94, 77));
        btnPatatas.setMinimumSize(new java.awt.Dimension(94, 77));
        btnPatatas.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlEntrantes.add(btnPatatas);

        btnEmpanadillas.setAlignmentY(0.0F);
        btnEmpanadillas.setMaximumSize(new java.awt.Dimension(94, 77));
        btnEmpanadillas.setMinimumSize(new java.awt.Dimension(94, 77));
        btnEmpanadillas.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlEntrantes.add(btnEmpanadillas);

        btnTortilla.setAlignmentY(0.0F);
        btnTortilla.setMaximumSize(new java.awt.Dimension(94, 77));
        btnTortilla.setMinimumSize(new java.awt.Dimension(94, 77));
        btnTortilla.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlEntrantes.add(btnTortilla);

        btnCaracoles.setAlignmentY(0.0F);
        btnCaracoles.setMaximumSize(new java.awt.Dimension(94, 77));
        btnCaracoles.setMinimumSize(new java.awt.Dimension(94, 77));
        btnCaracoles.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlEntrantes.add(btnCaracoles);

        pnlProductos.add(pnlEntrantes, "cardEntrantes");

        pnlPostres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlPostres.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 4));

        btnBizcocho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/bizcocho.png"))); // NOI18N
        btnBizcocho.setAlignmentY(0.0F);
        btnBizcocho.setMaximumSize(new java.awt.Dimension(94, 77));
        btnBizcocho.setMinimumSize(new java.awt.Dimension(94, 77));
        btnBizcocho.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlPostres.add(btnBizcocho);

        btnTortitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/tortitas.png"))); // NOI18N
        btnTortitas.setAlignmentY(0.0F);
        btnTortitas.setMaximumSize(new java.awt.Dimension(94, 77));
        btnTortitas.setMinimumSize(new java.awt.Dimension(94, 77));
        btnTortitas.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlPostres.add(btnTortitas);

        btnMousseChoco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/mousseChoco.png"))); // NOI18N
        btnMousseChoco.setAlignmentY(0.0F);
        btnMousseChoco.setMaximumSize(new java.awt.Dimension(94, 77));
        btnMousseChoco.setMinimumSize(new java.awt.Dimension(94, 77));
        btnMousseChoco.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlPostres.add(btnMousseChoco);

        btnMousseFresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/mousseFresa.png"))); // NOI18N
        btnMousseFresa.setAlignmentY(0.0F);
        btnMousseFresa.setMaximumSize(new java.awt.Dimension(94, 77));
        btnMousseFresa.setMinimumSize(new java.awt.Dimension(94, 77));
        btnMousseFresa.setPreferredSize(new java.awt.Dimension(94, 77));
        pnlPostres.add(btnMousseFresa);

        pnlProductos.add(pnlPostres, "cardPostres");

        pnlSeleccion.add(pnlProductos);

        pnlCategorias.setBackground(new java.awt.Color(255, 255, 255));
        pnlCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        pnlCategorias.setForeground(new java.awt.Color(204, 0, 51));
        pnlCategorias.setMaximumSize(new java.awt.Dimension(500, 185));
        pnlCategorias.setMinimumSize(new java.awt.Dimension(500, 185));
        pnlCategorias.setPreferredSize(new java.awt.Dimension(500, 185));
        pnlCategorias.setLayout(new java.awt.GridLayout(2, 5));

        btnCafes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/cafes.png"))); // NOI18N
        btnCafes.setAlignmentY(0.0F);
        btnCafes.setMaximumSize(new java.awt.Dimension(95, 86));
        btnCafes.setMinimumSize(new java.awt.Dimension(95, 86));
        btnCafes.setPreferredSize(new java.awt.Dimension(95, 86));
        btnCafes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCafesActionPerformed(evt);
            }
        });
        pnlCategorias.add(btnCafes);

        btnBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/bebidas.png"))); // NOI18N
        btnBebidas.setAlignmentY(0.0F);
        btnBebidas.setMaximumSize(new java.awt.Dimension(95, 86));
        btnBebidas.setMinimumSize(new java.awt.Dimension(95, 86));
        btnBebidas.setPreferredSize(new java.awt.Dimension(95, 86));
        btnBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebidasActionPerformed(evt);
            }
        });
        pnlCategorias.add(btnBebidas);

        btnHamburguesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/hamburguesas.png"))); // NOI18N
        btnHamburguesas.setAlignmentY(0.0F);
        btnHamburguesas.setMaximumSize(new java.awt.Dimension(95, 86));
        btnHamburguesas.setMinimumSize(new java.awt.Dimension(95, 86));
        btnHamburguesas.setPreferredSize(new java.awt.Dimension(95, 86));
        btnHamburguesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamburguesasActionPerformed(evt);
            }
        });
        pnlCategorias.add(btnHamburguesas);

        btnBocadillos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/bocadillo.png"))); // NOI18N
        btnBocadillos.setAlignmentY(0.0F);
        btnBocadillos.setMaximumSize(new java.awt.Dimension(95, 86));
        btnBocadillos.setMinimumSize(new java.awt.Dimension(95, 86));
        btnBocadillos.setPreferredSize(new java.awt.Dimension(95, 86));
        btnBocadillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBocadillosActionPerformed(evt);
            }
        });
        pnlCategorias.add(btnBocadillos);

        btnEnsaladas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/ensalada.png"))); // NOI18N
        btnEnsaladas.setAlignmentY(0.0F);
        btnEnsaladas.setMaximumSize(new java.awt.Dimension(95, 86));
        btnEnsaladas.setMinimumSize(new java.awt.Dimension(95, 86));
        btnEnsaladas.setPreferredSize(new java.awt.Dimension(95, 86));
        btnEnsaladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnsaladasActionPerformed(evt);
            }
        });
        pnlCategorias.add(btnEnsaladas);

        btnEntrantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/entrante.png"))); // NOI18N
        btnEntrantes.setAlignmentY(0.0F);
        btnEntrantes.setMaximumSize(new java.awt.Dimension(95, 86));
        btnEntrantes.setMinimumSize(new java.awt.Dimension(95, 86));
        btnEntrantes.setPreferredSize(new java.awt.Dimension(95, 86));
        btnEntrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrantesActionPerformed(evt);
            }
        });
        pnlCategorias.add(btnEntrantes);

        btnPostres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/postre.png"))); // NOI18N
        btnPostres.setAlignmentY(0.0F);
        btnPostres.setMaximumSize(new java.awt.Dimension(95, 86));
        btnPostres.setMinimumSize(new java.awt.Dimension(95, 86));
        btnPostres.setPreferredSize(new java.awt.Dimension(95, 86));
        btnPostres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostresActionPerformed(evt);
            }
        });
        pnlCategorias.add(btnPostres);

        jButton36.setBackground(new java.awt.Color(255, 255, 255));
        jButton36.setAlignmentY(0.0F);
        jButton36.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton36.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton36.setPreferredSize(new java.awt.Dimension(50, 50));
        pnlCategorias.add(jButton36);

        jButton37.setBackground(new java.awt.Color(255, 255, 255));
        jButton37.setAlignmentY(0.0F);
        jButton37.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton37.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton37.setPreferredSize(new java.awt.Dimension(50, 50));
        pnlCategorias.add(jButton37);

        jButton38.setBackground(new java.awt.Color(255, 255, 255));
        jButton38.setAlignmentY(0.0F);
        jButton38.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton38.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton38.setPreferredSize(new java.awt.Dimension(50, 50));
        pnlCategorias.add(jButton38);

        pnlSeleccion.add(pnlCategorias);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        panelInicio.add(pnlSeleccion, gridBagConstraints);

        pnlNumeros.setBackground(new java.awt.Color(255, 255, 255));
        pnlNumeros.setLayout(new java.awt.GridBagLayout());

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotal.setText("Total:");
        pnlNumeros.add(lblTotal, new java.awt.GridBagConstraints());

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlNumeros.add(txtTotal, gridBagConstraints);

        btn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn1.setText("1");
        btn1.setToolTipText("");
        btn1.setMaximumSize(new java.awt.Dimension(75, 55));
        btn1.setMinimumSize(new java.awt.Dimension(75, 55));
        btn1.setPreferredSize(new java.awt.Dimension(75, 55));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        pnlNumeros.add(btn1, gridBagConstraints);

        btn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn2.setText("2");
        btn2.setMaximumSize(new java.awt.Dimension(75, 55));
        btn2.setMinimumSize(new java.awt.Dimension(75, 55));
        btn2.setPreferredSize(new java.awt.Dimension(75, 55));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        pnlNumeros.add(btn2, gridBagConstraints);

        btn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn3.setText("3");
        btn3.setMaximumSize(new java.awt.Dimension(75, 55));
        btn3.setMinimumSize(new java.awt.Dimension(75, 55));
        btn3.setPreferredSize(new java.awt.Dimension(75, 55));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        pnlNumeros.add(btn3, gridBagConstraints);

        btn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn4.setText("4");
        btn4.setToolTipText("");
        btn4.setMaximumSize(new java.awt.Dimension(75, 55));
        btn4.setMinimumSize(new java.awt.Dimension(75, 55));
        btn4.setPreferredSize(new java.awt.Dimension(75, 55));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlNumeros.add(btn4, gridBagConstraints);

        btn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn5.setText("5");
        btn5.setMaximumSize(new java.awt.Dimension(75, 55));
        btn5.setMinimumSize(new java.awt.Dimension(75, 55));
        btn5.setPreferredSize(new java.awt.Dimension(75, 55));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        pnlNumeros.add(btn5, gridBagConstraints);

        btn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn6.setText("6");
        btn6.setMaximumSize(new java.awt.Dimension(75, 55));
        btn6.setMinimumSize(new java.awt.Dimension(75, 55));
        btn6.setPreferredSize(new java.awt.Dimension(75, 55));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        pnlNumeros.add(btn6, gridBagConstraints);

        btn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn7.setText("7");
        btn7.setMaximumSize(new java.awt.Dimension(75, 55));
        btn7.setMinimumSize(new java.awt.Dimension(75, 55));
        btn7.setPreferredSize(new java.awt.Dimension(75, 55));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlNumeros.add(btn7, gridBagConstraints);

        btn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn8.setText("8");
        btn8.setMaximumSize(new java.awt.Dimension(75, 55));
        btn8.setMinimumSize(new java.awt.Dimension(75, 55));
        btn8.setPreferredSize(new java.awt.Dimension(75, 55));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        pnlNumeros.add(btn8, gridBagConstraints);

        btn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn9.setText("9");
        btn9.setMaximumSize(new java.awt.Dimension(75, 55));
        btn9.setMinimumSize(new java.awt.Dimension(75, 55));
        btn9.setPreferredSize(new java.awt.Dimension(75, 55));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        pnlNumeros.add(btn9, gridBagConstraints);

        btn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn0.setText("0");
        btn0.setMaximumSize(new java.awt.Dimension(75, 55));
        btn0.setMinimumSize(new java.awt.Dimension(75, 55));
        btn0.setPreferredSize(new java.awt.Dimension(75, 55));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        pnlNumeros.add(btn0, gridBagConstraints);

        btnComa.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnComa.setText(".");
        btnComa.setMaximumSize(new java.awt.Dimension(75, 55));
        btnComa.setMinimumSize(new java.awt.Dimension(75, 55));
        btnComa.setPreferredSize(new java.awt.Dimension(75, 55));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        pnlNumeros.add(btnComa, gridBagConstraints);

        btnDescuento.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDescuento.setText("%");
        btnDescuento.setMaximumSize(new java.awt.Dimension(80, 60));
        btnDescuento.setMinimumSize(new java.awt.Dimension(80, 60));
        btnDescuento.setName(""); // NOI18N
        btnDescuento.setPreferredSize(new java.awt.Dimension(75, 55));
        btnDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescuentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        pnlNumeros.add(btnDescuento, gridBagConstraints);

        bntMas.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bntMas.setText("+");
        bntMas.setMaximumSize(new java.awt.Dimension(75, 55));
        bntMas.setMinimumSize(new java.awt.Dimension(75, 55));
        bntMas.setPreferredSize(new java.awt.Dimension(75, 55));
        bntMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        pnlNumeros.add(bntMas, gridBagConstraints);

        btnMenos.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnMenos.setText("-");
        btnMenos.setMaximumSize(new java.awt.Dimension(75, 55));
        btnMenos.setMinimumSize(new java.awt.Dimension(75, 55));
        btnMenos.setPreferredSize(new java.awt.Dimension(75, 55));
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        pnlNumeros.add(btnMenos, gridBagConstraints);

        btnArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/arriba.png"))); // NOI18N
        btnArriba.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnArriba.setMaximumSize(new java.awt.Dimension(75, 55));
        btnArriba.setMinimumSize(new java.awt.Dimension(75, 55));
        btnArriba.setPreferredSize(new java.awt.Dimension(75, 55));
        btnArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArribaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        pnlNumeros.add(btnArriba, gridBagConstraints);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/delete.png"))); // NOI18N
        btnEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEliminar.setMaximumSize(new java.awt.Dimension(75, 55));
        btnEliminar.setMinimumSize(new java.awt.Dimension(75, 55));
        btnEliminar.setPreferredSize(new java.awt.Dimension(75, 55));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlNumeros.add(btnEliminar, gridBagConstraints);

        btnAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/abajo.png"))); // NOI18N
        btnAbajo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAbajo.setMaximumSize(new java.awt.Dimension(75, 55));
        btnAbajo.setMinimumSize(new java.awt.Dimension(75, 55));
        btnAbajo.setPreferredSize(new java.awt.Dimension(75, 55));
        btnAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbajoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        pnlNumeros.add(btnAbajo, gridBagConstraints);

        btnCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/cobrar.png"))); // NOI18N
        btnCobrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCobrar.setMaximumSize(new java.awt.Dimension(75, 90));
        btnCobrar.setMinimumSize(new java.awt.Dimension(75, 90));
        btnCobrar.setPreferredSize(new java.awt.Dimension(75, 90));
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        pnlNumeros.add(btnCobrar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panelInicio.add(pnlNumeros, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoClienteActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

     /**
     * Botón que desplaza hacia arriba la fila seleccionada de la tabla
     * @param evt 
     */
    private void btnArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArribaActionPerformed
        if ( modeloTbl.getRowCount() > 1 ) // si la tabla tiene más de un elemento
            if (tblCompra.getSelectedRow() != 0) //si no está ya la primera fila seleccionada
                tblCompra.setRowSelectionInterval(tblCompra.getSelectedRow()-1, tblCompra.getSelectedRow()-1); //selecciona la fila anterior de la seleccionada
    }//GEN-LAST:event_btnArribaActionPerformed

    private void btnCafesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCafesActionPerformed
        CardLayout cl = (CardLayout)(pnlProductos.getLayout());
        cl.show(pnlProductos, "cardCafes");
    }//GEN-LAST:event_btnCafesActionPerformed

    private void btnBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebidasActionPerformed
        CardLayout cl = (CardLayout)(pnlProductos.getLayout());
        cl.show(pnlProductos, "cardBebidas");
    }//GEN-LAST:event_btnBebidasActionPerformed

    private void btnHamburguesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguesasActionPerformed
        CardLayout cl = (CardLayout)(pnlProductos.getLayout());
        cl.show(pnlProductos, "cardHamburguesas");
    }//GEN-LAST:event_btnHamburguesasActionPerformed

    private void btnBocadillosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBocadillosActionPerformed
        CardLayout cl = (CardLayout)(pnlProductos.getLayout());
        cl.show(pnlProductos, "cardBocadillos"); 
    }//GEN-LAST:event_btnBocadillosActionPerformed

    private void btnEnsaladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnsaladasActionPerformed
        CardLayout cl = (CardLayout)(pnlProductos.getLayout());
        cl.show(pnlProductos, "cardEnsaladas"); 
    }//GEN-LAST:event_btnEnsaladasActionPerformed

    private void btnEntrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrantesActionPerformed
        CardLayout cl = (CardLayout)(pnlProductos.getLayout());
        cl.show(pnlProductos, "cardEntrantes"); 
    }//GEN-LAST:event_btnEntrantesActionPerformed

    private void btnPostresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostresActionPerformed
        CardLayout cl = (CardLayout)(pnlProductos.getLayout());
        cl.show(pnlProductos, "cardPostres"); 
    }//GEN-LAST:event_btnPostresActionPerformed

    private void btnPolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolloActionPerformed
        frame.setProducto(frame.getProductoById(22));
    }//GEN-LAST:event_btnPolloActionPerformed

    private void txtTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTicketActionPerformed
        //
    }//GEN-LAST:event_txtTicketActionPerformed
 
    /**
     * Botón que muestra los clientes registrados y rellena los cuadros de texto con el seleccionado
     * @param evt 
     */
    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
      String inputValue = (String) JOptionPane.showInputDialog(getFrame(), "Seleccione el cliente:", "Clientes", JOptionPane.DEFAULT_OPTION,  new javax.swing.ImageIcon(getClass().getResource("/seas/multinacional/iconos/cliente.png")), acciones.getClientes(), acciones.getClientes()[0] );
      if (inputValue != null) {
        String[] texto = acciones.setClientInTextBoxes(inputValue);
        txtCodigoCliente.setText(texto[0]); //id
        txtNombre.setText(texto[1]); //nombre y apellidos
        frame.setCliente(acciones.getClienteById(Integer.parseInt(texto[0])));
      }
    }//GEN-LAST:event_btnClienteActionPerformed

    // Botones de la CANTIDAD
    
    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (frame.getCantidad() != 0) {
            String cadenaResultante = String.valueOf(frame.getCantidad()) +   String.valueOf(7);
            frame.setCantidad(Integer.parseInt(cadenaResultante));
        } else {
            frame.setCantidad(7);
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (frame.getCantidad() != 0) {
            String cadenaResultante = String.valueOf(frame.getCantidad()) +   String.valueOf(8);
            frame.setCantidad(Integer.parseInt(cadenaResultante));
        } else {
            frame.setCantidad(8);
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if (frame.getCantidad() != 0) {
            String cadenaResultante = String.valueOf(frame.getCantidad()) +   String.valueOf(9);  
            frame.setCantidad(Integer.parseInt(cadenaResultante));
        } else {
            frame.setCantidad(9);
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (frame.getCantidad() != 0) {
            String cadenaResultante = String.valueOf(frame.getCantidad()) +   String.valueOf(4);  
            frame.setCantidad(Integer.parseInt(cadenaResultante));
        } else {
            frame.setCantidad(4);
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (frame.getCantidad() != 0) {
            String cadenaResultante = String.valueOf(frame.getCantidad()) +   String.valueOf(5);  
            frame.setCantidad(Integer.parseInt(cadenaResultante));
        } else {
            frame.setCantidad(5);
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (frame.getCantidad() != 0) {
            String cadenaResultante = String.valueOf(frame.getCantidad()) +   String.valueOf(6);  
            frame.setCantidad(Integer.parseInt(cadenaResultante));
        } else {
            frame.setCantidad(6);
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (frame.getCantidad() != 0) {
            String cadenaResultante = String.valueOf(frame.getCantidad()) +   String.valueOf(1);  
            frame.setCantidad(Integer.parseInt(cadenaResultante));
        } else {
            frame.setCantidad(1);
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (frame.getCantidad() != 0) {
            String cadenaResultante = String.valueOf(frame.getCantidad()) +   String.valueOf(2);  
            frame.setCantidad(Integer.parseInt(cadenaResultante));
        } else {
            frame.setCantidad(2);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (frame.getCantidad() != 0) {
            String cadenaResultante = String.valueOf(frame.getCantidad()) +   String.valueOf(3);  
            frame.setCantidad(Integer.parseInt(cadenaResultante));
        } else {
            frame.setCantidad(3);
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        if (frame.getCantidad() != 0) {
            String cadenaResultante = String.valueOf(frame.getCantidad()) +   String.valueOf(0);  
            frame.setCantidad(Integer.parseInt(cadenaResultante));
        } else {
            frame.setCantidad(0);
        }
    }//GEN-LAST:event_btn0ActionPerformed

    
    private void setPrecioTotal() {
        int filas = modeloTbl.getRowCount();
        float precioTotal = 0;
        for (int i = 0; i < filas; i++)
            precioTotal = precioTotal +  (Float)modeloTbl.getValueAt(i, 4);       
        txtTotal.setText(Float.toString(precioTotal));
    }
    // Botones de los PRODUCTOS
    
    private void btnAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmericanoActionPerformed
        frame.setProducto(frame.getProductoById(1));
        modeloTbl.addRow(new Object[]{frame.getCantidad(), frame.getProducto().getNombre(), frame.getProducto().getPrecio(), 0, frame.getCantidad()*frame.getProducto().getPrecio()}); 
        tblCompra.setRowSelectionInterval(modeloTbl.getRowCount()-1, modeloTbl.getRowCount()-1); //selecciona la última fila de la tabla
        idProductos.add(1);
        frame.setCantidad(0);
        setPrecioTotal();
        try {
            recopilarDatos();
        } catch (ParseException ex) {
            Logger.getLogger(PanelInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAmericanoActionPerformed

    private void btnLecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecheActionPerformed
        frame.setProducto(frame.getProductoById(2));
    }//GEN-LAST:event_btnLecheActionPerformed

    private void btnCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCappuccinoActionPerformed
        frame.setProducto(frame.getProductoById(3));
    }//GEN-LAST:event_btnCappuccinoActionPerformed

    private void btnMacchiatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMacchiatoActionPerformed
        frame.setProducto(frame.getProductoById(4));
    }//GEN-LAST:event_btnMacchiatoActionPerformed

    private void btnHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeladoActionPerformed
        frame.setProducto(frame.getProductoById(5));
    }//GEN-LAST:event_btnHeladoActionPerformed

    private void btnFrapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrapaActionPerformed
        frame.setProducto(frame.getProductoById(6));
    }//GEN-LAST:event_btnFrapaActionPerformed

    private void btnEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspressoActionPerformed
        frame.setProducto(frame.getProductoById(7));
    }//GEN-LAST:event_btnEspressoActionPerformed

    private void btnMochaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMochaActionPerformed
        frame.setProducto(frame.getProductoById(8));
    }//GEN-LAST:event_btnMochaActionPerformed

    private void btnChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChocolateActionPerformed
        frame.setProducto(frame.getProductoById(9));
    }//GEN-LAST:event_btnChocolateActionPerformed

    private void btnRefrescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescoActionPerformed
        frame.setProducto(frame.getProductoById(10));
    }//GEN-LAST:event_btnRefrescoActionPerformed

    private void btnCervezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCervezaActionPerformed
        frame.setProducto(frame.getProductoById(11));
    }//GEN-LAST:event_btnCervezaActionPerformed

    private void btnVinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVinoActionPerformed
        frame.setProducto(frame.getProductoById(12));
    }//GEN-LAST:event_btnVinoActionPerformed

    private void btnTintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTintoActionPerformed
        frame.setProducto(frame.getProductoById(13));
    }//GEN-LAST:event_btnTintoActionPerformed

    private void btnZumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZumoActionPerformed
        frame.setProducto(frame.getProductoById(14));
    }//GEN-LAST:event_btnZumoActionPerformed

    private void btnAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAguaActionPerformed
        frame.setProducto(frame.getProductoById(15));
    }//GEN-LAST:event_btnAguaActionPerformed

    private void btnSetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetasActionPerformed
        frame.setProducto(frame.getProductoById(16));
    }//GEN-LAST:event_btnSetasActionPerformed

    private void btnQuesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuesoActionPerformed
        frame.setProducto(frame.getProductoById(17));
    }//GEN-LAST:event_btnQuesoActionPerformed

    private void btnBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaconActionPerformed
        frame.setProducto(frame.getProductoById(18));
    }//GEN-LAST:event_btnBaconActionPerformed

    private void btnPicanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPicanteActionPerformed
        frame.setProducto(frame.getProductoById(19));
    }//GEN-LAST:event_btnPicanteActionPerformed

    private void btnHuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuevoActionPerformed
        frame.setProducto(frame.getProductoById(20));
    }//GEN-LAST:event_btnHuevoActionPerformed

    private void btnTrufaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrufaActionPerformed
        frame.setProducto(frame.getProductoById(21));
    }//GEN-LAST:event_btnTrufaActionPerformed

    private void btnMiniBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiniBurgerActionPerformed
        frame.setProducto(frame.getProductoById(23));
    }//GEN-LAST:event_btnMiniBurgerActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        acciones.cobrarPedido(descuentoAplicado, Float.parseFloat(txtTotal.getText())); //añadir en este metodo lo relacionado para guardar los datos de la tabla        
        //Elimina todas las filas de la tabla
        int filas = modeloTbl.getRowCount();
        for (int i = 1; i <= filas; i++)
            modeloTbl.removeRow(0);
        frame.cargarPanel(new PanelInicio(frame));
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void recopilarDatos() throws ParseException {
        // TICKET
        String [] vendedor = ((String) cbVendedor.getSelectedItem()).split("\\.");
        int idVendedor = Integer.parseInt(vendedor[0]);
        int idCliente = frame.getCliente().getId();
        float precio = Float.parseFloat(txtTotal.getText());
        Date fecha = dfDefault.parse(txtFecha.getText());
        // LINEAS
        java.sql.Date sqlFecha = new java.sql.Date(fecha.getTime());
        int idTicket = serviceTicket.saveTicket(idVendedor, idCliente, precio, sqlFecha); //Obtenemos el id del ticket y guardamos el ticket en la bbdd
        for(int i=0; i < modeloTbl.getRowCount(); i++){ //creamos las lineas
            int idProducto = (Integer) idProductos.get(i);
           // int unidades = modeloTbl.
            
            
                /** @param idTicket
                * @param idProducto
                * @param unidades
                * @param precioUnitario
                * @param descuento 
                */
        }
    }
    
    
    
    /**
     * Botón que modifica las filas de las tablas para aplicar el descuento correspondiente al cliente
     * 
     * @param evt 
     */
    private void btnDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentoActionPerformed
        //modificar las filas de las tablas para aplicar el descuento (SOLO SI HAY CLIENTE)
        if (frame.getCliente() != null && descuentoAplicado == false && frame.getCliente().getDescuento() != 0){
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que desea aplicar el descuento? \n Si acepta ya, el descuento no será aplicado a nuevos productos añadidos", "Aviso", JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                int filas = modeloTbl.getRowCount();
                float precioTotal = 0;
                for (int i = 0; i < filas; i++) {
                    modeloTbl.setValueAt(frame.getCliente().getDescuento(), i, 3);
                    modeloTbl.setValueAt((Float)modeloTbl.getValueAt(i, 4)-(Float)modeloTbl.getValueAt(i, 4)*frame.getCliente().getDescuento(), i, 4);
                    precioTotal = precioTotal +  (Float)modeloTbl.getValueAt(i, 4);
                }
                txtTotal.setText(Float.toString(precioTotal));
                this.descuentoAplicado = true;
            }
        } else {
          if (frame.getCliente() == null) {
              JOptionPane.showMessageDialog(null, "Para aplicar un descuento, debe seleccionar un cliente primero", "Mensaje informativo", JOptionPane.INFORMATION_MESSAGE);
          } else if(frame.getCliente().getDescuento() == 0) {
              JOptionPane.showMessageDialog(null, "El cliente seleccionado no tiene ningún descuento acumulado", "Mensaje informativo", JOptionPane.INFORMATION_MESSAGE);
          }     
        }
        
    }//GEN-LAST:event_btnDescuentoActionPerformed

    /**
     * Botón que desplaza hacia abajo la fila seleccionada de la tabla
     * @param evt 
     */
    private void btnAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajoActionPerformed
        if ( modeloTbl.getRowCount() > 1 ){ // si la tabla tiene más de un elemento
            if (tblCompra.getSelectedRow() !=  modeloTbl.getRowCount()-1) { //si no está ya la última fila seleccionada
                tblCompra.setRowSelectionInterval(tblCompra.getSelectedRow()+1, tblCompra.getSelectedRow()+1); //selecciona la fila posterior de la seleccionada
            }
        }
    }//GEN-LAST:event_btnAbajoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       if(modeloTbl.getRowCount()!=0) {
            modeloTbl.removeRow(tblCompra.getSelectedRow());
            idProductos.remove(tblCompra.getSelectedRow());
            if(modeloTbl.getRowCount()!=0)
                tblCompra.setRowSelectionInterval(modeloTbl.getRowCount()-1, modeloTbl.getRowCount()-1); //selecciona la última fila de la tabla
       }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void bntMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMasActionPerformed
        if (modeloTbl.getRowCount()!=0){
            modeloTbl.setValueAt((Integer)modeloTbl.getValueAt(tblCompra.getSelectedRow(), 0)+1, tblCompra.getSelectedRow(), 0); //cambiamos la cantidad
            //Cambiamos el precio:
            modeloTbl.setValueAt((Integer)modeloTbl.getValueAt(tblCompra.getSelectedRow(), 0)*(Float)modeloTbl.getValueAt(tblCompra.getSelectedRow(), 2), tblCompra.getSelectedRow(), 4);
            setPrecioTotal();
        }            
    }//GEN-LAST:event_bntMasActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        if (modeloTbl.getRowCount()!=0)
            if ((Integer)modeloTbl.getValueAt(tblCompra.getSelectedRow(), 0) != 1){
                modeloTbl.setValueAt((Integer)modeloTbl.getValueAt(tblCompra.getSelectedRow(), 0)-1, tblCompra.getSelectedRow(), 0);
                //Cambiamos el precio:
            modeloTbl.setValueAt((Integer)modeloTbl.getValueAt(tblCompra.getSelectedRow(), 0)*(Float)modeloTbl.getValueAt(tblCompra.getSelectedRow(), 2), tblCompra.getSelectedRow(), 4);
            setPrecioTotal();
            } else {
                modeloTbl.removeRow(tblCompra.getSelectedRow());
                idProductos.remove(tblCompra.getSelectedRow());
                setPrecioTotal();
                if(modeloTbl.getRowCount()!=0)
                    tblCompra.setRowSelectionInterval(modeloTbl.getRowCount()-1, modeloTbl.getRowCount()-1); //selecciona la última fila de la tabla
            }
    }//GEN-LAST:event_btnMenosActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cbVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVendedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntMas;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAbajo;
    private javax.swing.JButton btnAgua;
    private javax.swing.JButton btnAlbondigas;
    private javax.swing.JButton btnAmericano;
    private javax.swing.JButton btnArriba;
    private javax.swing.JButton btnBacon;
    private javax.swing.JButton btnBebidas;
    private javax.swing.JButton btnBizcocho;
    private javax.swing.JButton btnBocadillos;
    private javax.swing.JButton btnCafes;
    private javax.swing.JButton btnCalamares;
    private javax.swing.JButton btnCappuccino;
    private javax.swing.JButton btnCaracoles;
    private javax.swing.JButton btnCerveza;
    private javax.swing.JButton btnCesar;
    private javax.swing.JButton btnChocolate;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnComa;
    private javax.swing.JButton btnCroquetas;
    private javax.swing.JButton btnDescuento;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEmpanadillas;
    private javax.swing.JButton btnEnsaladas;
    private javax.swing.JButton btnEntrantes;
    private javax.swing.JButton btnEspresso;
    private javax.swing.JButton btnFrapa;
    private javax.swing.JButton btnFrutal;
    private javax.swing.JButton btnHamburguesas;
    private javax.swing.JButton btnHelado;
    private javax.swing.JButton btnHuevo;
    private javax.swing.JButton btnLeche;
    private javax.swing.JButton btnMacchiato;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMiniBurger;
    private javax.swing.JButton btnMixta;
    private javax.swing.JButton btnMocha;
    private javax.swing.JButton btnMousseChoco;
    private javax.swing.JButton btnMousseFresa;
    private javax.swing.JButton btnPatatas;
    private javax.swing.JButton btnPicante;
    private javax.swing.JButton btnPollo;
    private javax.swing.JButton btnPostres;
    private javax.swing.JButton btnQueso;
    private javax.swing.JButton btnRefresco;
    private javax.swing.JButton btnSerranito;
    private javax.swing.JButton btnSetas;
    private javax.swing.JButton btnTinto;
    private javax.swing.JButton btnTortilla;
    private javax.swing.JButton btnTortitas;
    private javax.swing.JButton btnTrufa;
    private javax.swing.JButton btnVegetal;
    private javax.swing.JButton btnVino;
    private javax.swing.JButton btnZumo;
    private javax.swing.JComboBox<String> cbVendedor;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCodigoCliente;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroTicket;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel pnlBebidas;
    private javax.swing.JPanel pnlBocadillos;
    private javax.swing.JPanel pnlCafes;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlCompra;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlEnsaladas;
    private javax.swing.JPanel pnlEntrantes;
    private javax.swing.JPanel pnlHamburguesas;
    private javax.swing.JPanel pnlNumeros;
    private javax.swing.JPanel pnlPostres;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JPanel pnlSeleccion;
    private javax.swing.JTable tblCompra;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTicket;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
