/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seas.multinacional.vistas;

import java.util.ArrayList;
import seas.multinacional.controlador.ServiceCliente;
import seas.multinacional.principal.MultinacionalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class PanelBajaClientes extends javax.swing.JPanel {
    
    private MultinacionalFrame frame;
    private ServiceCliente acciones;
    /**
     * Creates new form PanelBajaClientes
     */
    public PanelBajaClientes(MultinacionalFrame frame) {
        this.frame = frame;
        this.acciones = new ServiceCliente(this);
        initComponents(); 
        //Asociar el modelo de lista al JList
        lstClientes.setModel(acciones.getClientesList());
    }
    
    public MultinacionalFrame getFrame() {
        return frame;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstClientes = new javax.swing.JList<>();
        btnEliminar = new javax.swing.JButton();

        jScrollPane1.setViewportView(lstClientes);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnEliminar)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

     /**
     * Botón que activa la eliminación de un cliente
     * @param evt 
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     if(!lstClientes.isSelectionEmpty()) {
        // ArrayList posIdClientes = acciones.getPosIdCliente();
        //posIdCliente.remove(index);
        acciones.deleteCliente(acciones.getIdSelected(lstClientes.getSelectedIndex()));
        lstClientes.setModel(acciones.getClientesList());
     } else {
         JOptionPane.showMessageDialog(null, "Debes seleccionar algún cliente a eliminar.");    
     }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstClientes;
    // End of variables declaration//GEN-END:variables
}
