/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seas.multinacional.vistas;

import seas.multinacional.controlador.ServiceVendedor;
import seas.multinacional.principal.MultinacionalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class PanelBajaVendedores extends javax.swing.JPanel {
    
    private MultinacionalFrame frame;
    private ServiceVendedor acciones;
    /**
     * Creates new form PanelBajaVendedores
     */
    public PanelBajaVendedores(MultinacionalFrame frame) {
        this.frame = frame;
        acciones = new ServiceVendedor(this);
        initComponents(); 
        //Asociar el modelo de lista al JList
        lstVendedores.setModel(acciones.getVendedoresList());
    }
    
    public MultinacionalFrame getFrame() {
        return frame;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstVendedores = new javax.swing.JList<>();
        btnEliminar = new javax.swing.JButton();

        jScrollPane1.setViewportView(lstVendedores);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón que activa la eliminación de un vendedor
     * @param evt 
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     if(!lstVendedores.isSelectionEmpty()) {
        acciones.deleteVendedor(acciones.getIdSelected(lstVendedores.getSelectedIndex()));
        lstVendedores.setModel(acciones.getVendedoresList());
     } else {
         JOptionPane.showMessageDialog(null, "Debes seleccionar algún cliente a eliminar.");    
     }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstVendedores;
    // End of variables declaration//GEN-END:variables
}
