package seas.multinacional.vistas;

import seas.multinacional.controlador.ServiceVendedor;
import seas.multinacional.principal.MultinacionalFrame;
import javax.swing.JTextField;

/**
 * Clase con el panel de alta de clientes.
 * 
 * @author maria
 */
public class PanelAltaVendedores extends javax.swing.JPanel {

    private MultinacionalFrame frame;
    private ServiceVendedor acciones;
    /**
     * Creates new form PanelAltaClientes
     */
    public PanelAltaVendedores(MultinacionalFrame frame) {
        initComponents();
        this.frame = frame;
        this.acciones = new ServiceVendedor(this);    
    }
    
    public MultinacionalFrame getFrame() {
        return frame;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public JTextField getTxtApellido1() {
        return txtApellido1;
    }

    public JTextField getTxtApellido2() {
        return txtApellido2;
    }
    
    public JTextField getTxtClave() {
        return txtClave;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblEnunciado = new javax.swing.JLabel();

        setLayout(null);

        lblNombre.setText("Nombre");
        add(lblNombre);
        lblNombre.setBounds(50, 60, 45, 16);

        lblApellido1.setText("Apellido 1");
        add(lblApellido1);
        lblApellido1.setBounds(50, 100, 56, 16);

        lblApellido2.setText("Apellido 2");
        add(lblApellido2);
        lblApellido2.setBounds(50, 140, 56, 16);
        add(txtNombre);
        txtNombre.setBounds(130, 60, 170, 22);
        add(txtApellido1);
        txtApellido1.setBounds(130, 100, 170, 22);
        add(txtApellido2);
        txtApellido2.setBounds(130, 140, 170, 22);

        lblClave.setText("Clave");
        add(lblClave);
        lblClave.setBounds(50, 180, 56, 16);
        add(txtClave);
        txtClave.setBounds(130, 180, 170, 22);

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        add(btnGuardar);
        btnGuardar.setBounds(250, 230, 110, 25);

        lblEnunciado.setText("Introduzca los datos del nuevo Vendedor:");
        add(lblEnunciado);
        lblEnunciado.setBounds(50, 20, 240, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        acciones.saveVendedor();
    }//GEN-LAST:event_btnGuardarMouseClicked
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblEnunciado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables



}
